# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "activerecord", "~> 7.0"

gem "rack", "~> 3.0"

gem "rackup", "~> 0.2.2"

gem "pry", "~> 0.14.1"

gem "require_all", "~> 3.0"

gem "sqlite3", "~> 1.5"
